### ISSUE TITLE
Twig 2: `composer require twig/twig` breaks on jasny/twig-extensions

### ISSUE THREAD

**Issue by inoas** [jasny/twig-extensions#14]
It seems the changes are not too big...
Is an update to require Twig 2.x  instead of 1.x planned any time?

**Comment by inoas** [comment]
@jasny would you be interested in a PR to bring `https://github.com/jasny/twig-extensions/issues/14` up to Twig 2.0 without deprecated uses and probably a release 2.0 that is non-BC?

**Comment by jasny** [comment]
@inoas Could you please try using Jasny Twig Extensions with Twig v2 and report any issues.

Pull requests are always appreciated. :smile:

**Comment by inoas** [comment]
I can try and see if it works out of the box after tinkering with composer.
If it does, it is `fine for now` - however, the non-fully-qualified-names (Twig-1-Style) are just there via class aliases in Twig-2, are (AFAIR) already deprecated and will be removed in Twig-3. So that would be the next step, right?

**Comment by inoas** [comment]
Closing as PR is open: https://github.com/jasny/twig-extensions/pull/15
