### ISSUE TITLE
twig-extensions 2.0: PHP 7.0 / Twig ^2.0 no-deprecations / Twig ^3.0 ready / PHP 7 Hints

### ISSUE THREAD

**Issue by inoas** [jasny/twig-extensions#16]
@jasny Let me know if you have interest in this. If you have I can try to prep a PR. It will be a bit bigger, though.

**Comment by jasny** [comment]
@inoas It should also remain working in Twig 1.0 for now. If you can make it run in both, it would be great.

**Comment by inoas** [comment]
@jasny Fixing deprecations introduced in ^2.0 would contradict being compatible with Twig ^1.0.

Because of that we could then require PHP 7.0 as a minimum and introduce php function return type hints and if desired, by you, flag classes `final`. All that is the reason you would need to release twig-extensions 2.0 then as all this is a non-BC change.

Removing deprecations would however mean that it is ready for Twig 3.0.
This is nothing we need in our project until Twig 3.0 hits, but as I am upgrading Twig based libraries that we use at the moment, it would be quite nice.

Feel free to close this issue if you have no interest in this (as of now).
