### ISSUE TITLE
Problem with preg_replace

### ISSUE THREAD

**Issue by mwoznowski** [jasny/twig-extensions#18]
Hello,
I try format string ex. 1234123412341234 to 1234-1234-1234-1234
`{{ row.code|preg_replace('/^(\d{4})(\d{4})(\d{4})(\d{4})$/', '$1-$2-$3-$4') }}`
but only show normal string without format
https://i.imgur.com/iPoixuA.png

**Comment by hacfi** [comment]
Hi @Matix8981,
the issue seems to be escaping with twig:
You need to use double backslashes `\\`:

`{{ row.code|preg_replace('/^(\\d{4})(\\d{4})(\\d{4})(\\d{4})$/', '$1-$2-$3-$4') }}`

**Comment by mwoznowski** [comment]
Thanks, this is work :)
