### ISSUE TITLE
localdate, localtime and localdatetime

### ISSUE THREAD

**Issue by sergiors** [jasny/twig-extensions#4]
Hi @jasny, I read the functions: `localdate`, `localtime` and `localdatetime`, and I Think could you use `twig/extensions` for that, because I think the behavior is the same:

https://github.com/twigphp/Twig-extensions/blob/master/lib/Twig/Extensions/Extension/Intl.php#L29

Some thing like this:

```
{{ 'now'|localizeddate('short', 'none') }}
{{ 'now'|localizeddate('none', 'short') }}
```

What do you think about it?
Sorry for my bad english

**Comment by jasny** [comment]
Yes it's pretty much the same, though this impl can do a few thing more. Not everybody is using Twig/Extensions though, so I am leaving it in. Wont hurt anybody.
