### ISSUE TITLE
Had to disable assertNoEval() for preg_get()

### ISSUE THREAD

**Issue by basepack** [jasny/twig-extensions#8]
Hi,

I am matching the weeknumber in this string: `Week 38 - 2016`.

So I write the following: `{% set weeknumber = week|preg_get('/Week (?<weeknumber>[0-9]{1,})/', "weeknumber") %}`. 

Works perfectly, however I had to comment out the `assertNoEval()` call for the `get()` function. Maybe you can take a closer look at the assertNoEval function?

**Comment by jasny** [comment]
Duplicate of #5
